### ISSUE TITLE
Support Versioning SHR

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/shr-grammar#10]
While we already support explicit versioning of grammars, we do not have an explicit mechanism for versioning the SHR.  We need to determine if SHR should be versioned as a whole (similar to FHIR) or if smaller pieces can be independently versioned (either at the namespace or element level).  If versioning at the namespace or element level, what does this mean for referenced elements?  E.g., if A is version 1 and has a field B that is version 1, then if B is updated to version 2, what happens to A?  When we version A, are we somehow tracking the versions of all fields included in A (and base classes, etc).  This complexity adds to the appeal of versioning SHR as a whole.

**Comment by markkramerus** [comment]
Discussed elsewhere.
