### ISSUE TITLE
"Abstract" keyword still not working

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-grammar#18]
CLI crashes when it hits "Abstract" -- it only accepts "Element" or "EntryElement"
This is in 5.0 Beta 6.

**Comment by Abhijay** [comment]
Hmm, I just tested it out locally and it didn't crash on my end. 

Just to clarify, the usage is "Abstract Element: ElementName"
Are you by any chance using the syntax "Abstract: ElementName"?

**Comment by markkramerus** [comment]
I was using Abstract: not Abstract Element:  So closing this bug.
