### ISSUE TITLE
EntryElement should be Entry Element (with space)

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-grammar#19]
For consistency with Abstract Element, Based on and other two-word keywords.

**Comment by Abhijay** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [EntryElement should be 'Entry Element'](https://trello.com/c/4ZEtoiX0/2-entryelement-should-be-entry-element)

**Comment by markkramerus** [comment]
Overcome by events in grammar 6.0. Will not fix in 5.x
