### ISSUE TITLE
Don't Allow Choice Options to Have Own Cardinality

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/shr-grammar#5]
When there is a choice (e.g., `Abc or Xyz`) allowing each option to have its own cardinality leads to complicated and/or ambiguous results, e.g.:
```
1..*  0..1 Abc or 1..5 Xyz
```

It also requires special handling for the most common use case (when each option _doesn't_ need its own cardinality:
```
1..* (Abc or Xyz) // parentheses needed to be clear that 1..* applies to both options
```

Instead, _don't_ allow choice options to have their own cardinalities -- it's too confusing and SHR doesn't seem to use/need it anyway.  This simplifies the grammar and the tooling:
```
1..* Abc or Xyz
```

**Comment by cmoesel** [comment]
This is addressed in the grammar_5 branch.

**Comment by markkramerus** [comment]
OBE. We clarified this in Grammar 6.0. Values (choice or no choice) don't have cardinality. Properties do.
